databases:
  - name: project_bank
    databaseName: project_bank
    user: project_bank
services:
  - type: web
    name: project-bank
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        value: "postgres://project_bank:password@project_bank_host:5432/project_bank"
      - key: RAILS_MASTER_KEY
        sync: false
